### ISSUE TITLE
MMM-HomeAssistant without apipassword

### ISSUE THREAD

**Issue by iorifly** [zuo000/MMM-HomeAssistant#1]
How to configure now that the new version of HA does not accept APIpassWord option?

**Comment by iorifly** [comment]
Already activated the apipassword, but I have msg error in HA

> Login attempt or request with invalid authentication from 192.168.1.159

> Login attempt or request with invalid authentication from 192.168.1.159
> 23:48 components/http/ban.py (WARNING) - a mensagem ocorreu pela primeira às 23:44 e apareceu 51 vezes

**Comment by zuo000** [comment]
can you share you configuration.yaml of HA?

**Comment by iorifly** [comment]
a part of the code ..

```
homeassistant:
  whitelist_external_dirs:
    - /tmp
    - /config/temp/
  auth_providers:
      - type: legacy_api_password
        api_password: "juere3027"
    

  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -22.7878
  longitude: -43.3031
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: -1161
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

default_config:

mobile_app:



homekit:
  filter:
    
    include_entities:
      - switch.sonoff_100016e09d #cafeteira
      - switch.luz_quintal
      - switch.sonoff_10002a37c6 # luz piscina
      - switch.sonoff_10009cdde7 # bomba cisterna
      - script.1567205208010
      - switch.sonoff_10009ce0eb # Palmeira Piscina
      - script.1548637033487 # ligar video game.
    exclude_domains:  
      - automation
      - script
      
# Enables the frontend
frontend:
  themes: !include themes.yaml
  javascript_version: latest

shell_command:
 snapshotv: ffmpeg -rtsp_transport tcp -r 25 -i rtsp://192.168.1.179:7447/5b689ac2e5dfd6a7490e44f9_0 -an -t 10 -c copy -map 0 -y -update 1 {{filename}}
 show_cam: bash /config/cam.sh
 playkodi: bash /config/playkodi.sh
 show_allcam: bash /config/allcam.sh
 
# Enables configuration UI
```
